#!/bin/sh

operation=$(echo -e "show\nadd\ngenerate" | dmenu -i -p "What to do?")

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

printf '%s\n' "${password_files[@]}"

case $operation in
		show)
				selection=$(printf '%s\n' "${password_files[@]}" | dmenu -i -p "What password?")
				pass $selection -c;;
		add)
				name=$(echo "" | dmenu -p "What name?")
				password=$(echo "" | dmenu -p "What password?")
				echo $password | pass insert $name;;
		generate)
				name=$(echo "" | dmenu -p "What name?")
				length=$(echo "" | dmenu -p "How long should the password be?")
				pass generate -n $length $name;;
esac
