#!/bin/sh

operation=$(echo -e "show\nadd\ngenerate" | dmenu -i -p "What to do?")

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )




case $operation in
		show)
				sel=()
				num=1
				for i in "${password_files[@]}"
				do
						sel+=("$num"": ""$i")
						let "num+=1"
				done
				selection=$(printf '%s\n' "${sel[@]}" | dmenu -i -l $num | awk '{print $2}')
				pass $selection -c;;
		add)
				name=$(echo "" | dmenu -p "What name?")
				password=$(echo "" | dmenu -p "What password?")
				echo $password | pass insert $name;;
		generate)
				name=$(echo "" | dmenu -p "What name?")
				length=$(echo "" | dmenu -p "How long should the password be?")
				pass generate $name -n $length -c;;
esac
