#!/bin/sh


prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files+=( "$prefix"/**/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )


showPassword() {
				sel=()
				num=1
				for i in "${password_files[@]}"
				do
					sel+=("$num"": ""$i")
					let "num+=1"
				done
				selection=$(printf '%s\n' "${sel[@]}" | dmenu -i -l $num | cut -d ' ' -f2)
				pass $selection -c
}

addPassword() {
				name=$(echo "" | dmenu -p "What name?")
				password=$(echo "" | dmenu -p "What password?")
				echo $password | pass insert -e $name
}
generatePassword() {
				name=$(echo "" | dmenu -p "What name?")
				length=$(echo "" | dmenu -p "How long should the password be?")
}

noOP() {
		operation=$(echo -e "show\nadd\ngenerate" | dmenu -i -p "What to do?")

		case $operation in
				"show")
						showPassword;;
				"add")
						addPassword;;
				"generate")
						generatePassword;;
		esac
}

printHelp() {
		echo "Usage: password <option>"
		echo "Options:"
		echo -e "No Option\tAction selection in dmenu\n"
		echo -e "\t-h\tPrint this\n"
		echo -e "\t-s\tShow Passwords\n"
		echo -e "\t-a\tAdd a Password\n"
		echo -e "\t-g\tGenerate a Password\n"
}
case $1 in
		"")
				noOP;;
		"-h")
				printHelp;;
		"-s")
				showPassword;;
		"-a")
				addPassword;;
		"-g")
				generatePassword;;
esac
